"""Behavioral tests for the public epistemic event contracts."""

import importlib.util
import json
import re
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).parent
MODULE_PATH = ROOT / "verify_epistemic_event.py"
SPEC = importlib.util.spec_from_file_location("verify_epistemic_event", MODULE_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("unable to load verifier module")
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)

EventError = MODULE.EventError
append_validated_record = MODULE.append_validated_record
canonical_record_bytes = MODULE.canonical_record_bytes
verify_event = MODULE.verify_event
verify_outcome = MODULE.verify_outcome
load_skill_event_map = MODULE.load_skill_event_map
verify_skill_event_map = MODULE.verify_skill_event_map

MAP_PATH = ROOT / "skill-event-map.json"
SENTINEL_DIR = ROOT / "sentinels"

SENTINEL_SHAPE = {
    "id", "skill", "event_kind", "scenario", "response",
    "expected_oracle", "failure_class", "oracle_rule",
}

# Per-skill sentinel corpus coverage, hand-maintained like EXPECTED_SKILLS.
# Each skill-event-map entry names its canonical RED sentinel; the corpus
# below pins the additional fixture-set members each skill's Oracle section
# specifies (v7 review F-015). operational-scenarios.json is the separate
# multi-case corpus with its own validator (score_sentinels.py --self-test)
# and is not a per-skill sentinel file.
CORPUS_FAILURE_CLASSES = {
    "did-it-land": {
        "source-read-as-landed",
        "reverted-after-window-read-as-landed",
        "empty-observation-read-as-success",
        "stand-in-control-read-as-production-proof",
    },
    "health": {
        "unknown-aggregated-as-ok",
        "registry-unreachable-claimed-complete",
        "credential-failure-read-as-ok",
        "probe-tool-absent-read-as-ok",
        "probe-timeout-read-as-ok",
        "undeclared-bound-read-as-ok",
    },
    "triage": {
        "plausible-without-observation",
        "lying-readout-read-as-not-broken",
    },
}


def root_skills_reference() -> Path:
    """Resolve the tracked root skills alias on symlink-capable and Windows checkouts."""
    skills_alias = ROOT.parents[3] / "skills"
    if skills_alias.is_dir():
        skills_root = skills_alias
    else:
        skills_root = skills_alias.parent / skills_alias.read_text(encoding="utf-8").strip()
    # .resolve() is load-bearing: the repo-root `skills` alias is a Windows
    # JUNCTION, so .parent on the alias yields the repo root rather than the
    # package root. Same trap that made an earlier census report 0 dangling
    # links while 7 were dead.
    return skills_root.resolve().parent / "reference" / "epistemic-data-collection.md"


ROOT_REFERENCE = root_skills_reference()
PACKAGE_REFERENCE = (
    ROOT.parents[1]
    / "reference"
    / "epistemic-data-collection.md"
)
# BEGIN GENERATED SKILL INVENTORY
# Generated by sync_skill_surfaces.py from the skills/ glob.
# BEGIN GENERATED SKILL INVENTORY EXPECTED_SKILLS
# Generated by sync_skill_surfaces.py from the skills/ glob.
EXPECTED_SKILLS = {
    'context-audit', 'decision-ledger', 'did-it-land', 'epistemic', 'evidence-locked-uat', 'gauntlet', 'health', 'manifest', 'metacognate', 'open-questions', 'outsource', 'perspective', 'recon', 'resolve', 'triage', 'watch', 'write-goal',
}
# END GENERATED SKILL INVENTORY EXPECTED_SKILLS
# END GENERATED SKILL INVENTORY


def load(relative_path: str) -> dict:
    with (ROOT / "examples" / relative_path).open(encoding="utf-8") as handle:
        return json.load(handle)


def load_outcome_schema() -> dict:
    with (ROOT / "epistemic-outcome.schema.json").open(encoding="utf-8") as handle:
        return json.load(handle)


def load_skill_event_map_schema() -> dict:
    with (ROOT / "skill-event-map.schema.json").open(encoding="utf-8") as handle:
        return json.load(handle)


def schema_matches(instance: object, schema: dict) -> bool:
    """Evaluate the JSON Schema keywords exercised by public contracts."""
    if "const" in schema and instance != schema["const"]:
        return False
    if "enum" in schema and instance not in schema["enum"]:
        return False
    if "type" in schema:
        allowed_types = schema["type"]
        if not isinstance(allowed_types, list):
            allowed_types = [allowed_types]
        type_matches = {
            "object": isinstance(instance, dict),
            "array": isinstance(instance, list),
            "string": isinstance(instance, str),
            "number": isinstance(instance, (int, float)) and not isinstance(instance, bool),
            "null": instance is None,
        }
        if not any(type_matches.get(name, False) for name in allowed_types):
            return False
    if "required" in schema:
        if not isinstance(instance, dict) or not set(schema["required"]) <= set(instance):
            return False
    if schema.get("additionalProperties") is False and isinstance(instance, dict):
        if set(instance) - set(schema.get("properties", {})):
            return False
    if "properties" in schema and isinstance(instance, dict):
        for key, property_schema in schema["properties"].items():
            if key in instance and not schema_matches(instance[key], property_schema):
                return False
    if isinstance(instance, list):
        if len(instance) < schema.get("minItems", 0):
            return False
        if "maxItems" in schema and len(instance) > schema["maxItems"]:
            return False
        if "items" in schema and any(not schema_matches(item, schema["items"]) for item in instance):
            return False
    if "pattern" in schema and isinstance(instance, str) and not re.search(schema["pattern"], instance):
        return False
    if "not" in schema and schema_matches(instance, schema["not"]):
        return False
    for branch in schema.get("allOf", []):
        if not schema_matches(instance, branch):
            return False
    if "oneOf" in schema and sum(schema_matches(instance, branch) for branch in schema["oneOf"]) != 1:
        return False
    if "contains" in schema and isinstance(instance, list):
        matches = sum(schema_matches(item, schema["contains"]) for item in instance)
        if matches < schema.get("minContains", 1):
            return False
        if "maxContains" in schema and matches > schema["maxContains"]:
            return False
    if "if" in schema and schema_matches(instance, schema["if"]):
        if "then" in schema and not schema_matches(instance, schema["then"]):
            return False
    return True


class EpistemicEventContractTests(unittest.TestCase):
    def test_map_covers_every_packaged_skill_once(self):
        mapping = load_skill_event_map(MAP_PATH)
        verify_skill_event_map(mapping)
        names = [item["skill"] for item in mapping["skills"]]
        self.assertEqual(set(names), EXPECTED_SKILLS)
        self.assertEqual(len(names), len(set(names)))

    def test_every_skill_has_a_non_routine_eligibility_rule(self):
        mapping = load_skill_event_map(MAP_PATH)
        for item in mapping["skills"]:
            self.assertNotEqual(item["eligible_when"], "every invocation")
            self.assertTrue(item["sentinel_fixture"])

    def test_schema_and_verifier_reject_duplicate_skill_map_rows(self):
        mapping = load_skill_event_map(MAP_PATH)
        broken = json.loads(json.dumps(mapping))
        broken["skills"][1]["skill"] = "using-epistemic-skills"
        self.assertFalse(schema_matches(broken, load_skill_event_map_schema()))
        with self.assertRaisesRegex(EventError, "SCHEMA_VIOLATION"):
            verify_skill_event_map(broken)

    def test_schema_and_verifier_reject_valid_field_wrong_cross_pairing(self):
        mapping = load_skill_event_map(MAP_PATH)
        broken = json.loads(json.dumps(mapping))
        broken["skills"][0]["event_kinds"] = ["state-readout"]
        self.assertFalse(schema_matches(broken, load_skill_event_map_schema()))
        with self.assertRaisesRegex(EventError, "SCHEMA_VIOLATION"):
            verify_skill_event_map(broken)

    def test_event_kind_parity_across_schema_verifier_and_map(self):
        # SCHEMA/VERIFIER/MAP PARITY, ported from the calibration contract's
        # supersession-parity pattern (verify_calibration.py self_test). A
        # producer validates events against the published JSON Schema; a
        # consumer runs the verifier; the skill-event map is the closed
        # per-skill mandate. Where the surfaces disagree, a producer gets a
        # false PASS or a consumer refuses bytes a skill is mandated to emit.
        #
        # Parity is SUBSET-shaped, not three-way equality: every kind the map
        # mandates must be accepted by the schema and the verifier (those two
        # must remain one set), and the retired-but-valid v1 vocabulary
        # (pairing-decision, consumer-gate-outcome, merge-ruling) must stay
        # accepted so stored epistemic-event@1 records keep validating.
        # Equality with the map's union would force removing the retained
        # vocabulary and break consumers that revalidate stored events.
        #
        # HONEST SCOPE OF THIS ORACLE: it reads the schema and map documents,
        # so it establishes that the surfaces DECLARE a consistent closed
        # vocabulary — not that any JSON Schema implementation enforces it
        # (the same scope the calibration parity pin honestly claims).
        retained_v1_vocabulary = {
            "pairing-decision", "consumer-gate-outcome", "merge-ruling",
        }
        with (ROOT / "epistemic-event.schema.json").open(encoding="utf-8") as handle:
            schema_kinds = set(json.load(handle)["properties"]["event_kind"]["enum"])
        mandated_kinds = {
            kind
            for item in load_skill_event_map(MAP_PATH)["skills"]
            for kind in item["event_kinds"]
        }
        self.assertEqual(
            schema_kinds,
            set(MODULE.EVENT_KINDS),
            "schema/verifier parity: the epistemic-event schema event_kind enum "
            "and the verifier EVENT_KINDS disagree: "
            f"{sorted(schema_kinds ^ set(MODULE.EVENT_KINDS))}",
        )
        self.assertTrue(
            mandated_kinds <= set(MODULE.EVENT_KINDS),
            "verifier/map coverage: every skill-event-map mandated event_kind "
            "must be accepted by the verifier; missing: "
            f"{sorted(mandated_kinds - set(MODULE.EVENT_KINDS))}",
        )
        self.assertEqual(
            schema_kinds,
            mandated_kinds | retained_v1_vocabulary,
            "closed vocabulary: the schema enum must equal the map's mandated "
            "kinds plus exactly the retained v1 vocabulary — anything else is "
            "an unmandated, unretained kind that would let records no skill "
            "produces and no contract retains validate silently",
        )

    def test_every_sentinel_fixture_is_rejected_by_the_scoring_oracle(self):
        # The corpus shape test proves every sentinel DECLARES
        # expected_oracle == REJECT; this test executes each fixture through
        # the production scoring oracle (.github/scripts/score_sentinels.py)
        # and requires the actual verdict to match. A fixture the oracle
        # accepts is a planted failure class the suite cannot detect, so the
        # corpus and the oracle must move together.
        oracle_path = ROOT.parents[3] / ".github" / "scripts" / "score_sentinels.py"
        spec = importlib.util.spec_from_file_location("score_sentinels", oracle_path)
        if spec is None or spec.loader is None:
            raise RuntimeError("unable to load the scoring oracle module")
        oracle_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(oracle_module)
        for path in sorted(SENTINEL_DIR.glob("*.json")):
            if path.name == "operational-scenarios.json":
                continue
            with path.open(encoding="utf-8") as handle:
                fixture = json.load(handle)
            self.assertEqual(
                oracle_module.oracle(fixture),
                fixture["expected_oracle"],
                f"{path.name}: the scoring oracle does not produce the "
                f"expected verdict; the planted failure class is not "
                f"actually detected",
            )

    def test_sentinel_corpus_files_follow_the_closed_sentinel_shape(self):
        by_skill = {}
        for path in sorted(SENTINEL_DIR.glob("*.json")):
            if path.name == "operational-scenarios.json":
                continue
            with path.open(encoding="utf-8") as handle:
                fixture = json.load(handle)
            self.assertEqual(
                set(fixture),
                SENTINEL_SHAPE,
                f"{path.name}: sentinel shape drift",
            )
            self.assertEqual(fixture["id"], path.stem, f"{path.name}: id must match filename")
            self.assertEqual(
                fixture["expected_oracle"],
                "REJECT",
                f"{path.name}: per-skill sentinels are RED negative controls",
            )
            mapping = load_skill_event_map(MAP_PATH)
            entry = next(item for item in mapping["skills"] if item["skill"] == fixture["skill"])
            self.assertIn(
                fixture["event_kind"],
                entry["event_kinds"],
                f"{path.name}: event_kind claims {fixture['event_kind']!r}, "
                f"map allows {entry['event_kinds']}",
            )
            by_skill.setdefault(fixture["skill"], set()).add(fixture["failure_class"])
        for skill, expected_classes in sorted(CORPUS_FAILURE_CLASSES.items()):
            self.assertEqual(
                by_skill.get(skill, set()),
                expected_classes,
                f"{skill}: sentinel corpus does not match the Oracle-specified fixture set",
            )

    def test_schema_and_verifier_accept_the_closed_skill_event_map(self):
        mapping = load_skill_event_map(MAP_PATH)
        self.assertTrue(schema_matches(mapping, load_skill_event_map_schema()))
        verify_skill_event_map(mapping)

    def test_canonical_and_packaged_collection_references_match(self):
        self.assertEqual(
            ROOT_REFERENCE.read_bytes(),
            PACKAGE_REFERENCE.read_bytes(),
        )

    def test_calibratable_event_requires_probability_and_resolution_rule(self):
        record = load("valid/calibratable-event.json")
        verify_event(record)
        broken = {**record, "forecast": {**record["forecast"]}}
        del broken["forecast"]["probability"]
        with self.assertRaisesRegex(EventError, "SCHEMA_VIOLATION"):
            verify_event(broken)

    def test_observational_event_rejects_probability(self):
        with self.assertRaisesRegex(EventError, "ILLEGAL_EVENT_VARIANT"):
            verify_event(load("invalid/observational-with-probability.json"))

    def test_raw_content_keys_fail_closed(self):
        with self.assertRaisesRegex(EventError, "PROHIBITED_CONTENT"):
            verify_event(load("invalid/raw-content.json"))

    def test_equal_canonical_records_have_equal_bytes(self):
        left = load("valid/calibratable-event.json")
        right = dict(reversed(list(left.items())))
        self.assertEqual(canonical_record_bytes(left), canonical_record_bytes(right))

    def test_unknown_event_kind_fails_closed(self):
        with self.assertRaisesRegex(EventError, "SCHEMA_VIOLATION"):
            verify_event(load("invalid/unknown-event-kind.json"))

    def test_outcome_requires_independent_evidence_when_resolved(self):
        record = load("valid/outcome.json")
        verify_outcome(record)
        missing_evidence = {**record, "evidence_ref": None}
        with self.assertRaisesRegex(EventError, "SCHEMA_VIOLATION"):
            verify_outcome(missing_evidence)
        self_reported = {**record, "independence_class": "self-reported"}
        with self.assertRaisesRegex(EventError, "SCHEMA_VIOLATION"):
            verify_outcome(self_reported)

    def test_append_validated_record_requires_explicit_validated_record(self):
        record = load("valid/calibratable-event.json")
        with tempfile.TemporaryDirectory() as temporary_directory:
            output = Path(temporary_directory) / "records" / "events.jsonl"
            append_validated_record(record, output)
            self.assertEqual(output.read_bytes(), canonical_record_bytes(record))

    def test_schema_and_verifier_reject_resolved_outcomes_without_independent_evidence(self):
        record = load("valid/outcome.json")
        for broken in (
            {**record, "evidence_ref": None},
            {**record, "independence_class": "self-reported"},
        ):
            self.assertFalse(schema_matches(broken, load_outcome_schema()))
            with self.assertRaisesRegex(EventError, "SCHEMA_VIOLATION"):
                verify_outcome(broken)

    def test_schema_and_verifier_require_a_predecessor_for_superseded_outcomes(self):
        record = {**load("valid/outcome.json"), "resolution_status": "superseded", "supersedes": None}
        self.assertFalse(schema_matches(record, load_outcome_schema()))
        with self.assertRaisesRegex(EventError, "SCHEMA_VIOLATION"):
            verify_outcome(record)

    def test_verifier_rejects_a_self_superseding_outcome(self):
        record = load("valid/outcome.json")
        broken = {
            **record,
            "resolution_status": "superseded",
            "supersedes": record["observation_id"],
        }
        with self.assertRaisesRegex(EventError, "SCHEMA_VIOLATION"):
            verify_outcome(broken)

    def test_append_invalid_scalar_raises_a_controlled_event_error(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            output = Path(temporary_directory) / "events.jsonl"
            with self.assertRaisesRegex(EventError, "UNKNOWN_RECORD"):
                append_validated_record([], output)


if __name__ == "__main__":
    unittest.main()
